### ISSUE TITLE
bug in src/fitMLG.jl

### ISSUE THREAD

**Issue by RaphaelRaphael** [MurrellGroup/MultinomialLogisticGrowth#1]
Trying to launch src/fitMLG.jl I had to change

`dates = collect(minimum(count_df.date):maximum(count_df.date))
`
by

`dates = collect(minimum(count_df.date):Day(1):maximum(count_df.date))
`

to avoid an error

**Comment by RaphaelRaphael** [comment]
It appear that the script fitMLG.jl  do not run on the data provided.

**Comment by murrellb** [comment]
Thank you for reporting. Could be an updated dependency issue (especially after seeing your first comment in this thread) - I notice I did not commit my manifest, so the package versions will not be pinned to the ones I used. Please can you clarify what the error is on your side, and show me your current package versions, and I can look into it?

**Comment by murrellb** [comment]
I've just confirmed that, with the Manifest (which I've now added to the repo) it runs on a new Julia installation. Please try and clone the repo again, and then try the following, from the base directory of the repo:
```julia
using Pkg
Pkg.activate(".")
Pkg.instantiate()
```
And then if you're using a GPU for this (and I have only tested the GPU version) you might need to also:
```julia
Pkg.add("cuDNN")
```
Then restart your Julia kernel, and run the contents of `fitMLG.jl` directly in the REPL, and let me know if that works for you?

**Comment by RaphaelRaphael** [comment]
The code is now running perfectly, the issue was from the server I was working on. Sorry for that !

**Comment by RaphaelRaphael** [comment]
By the way the "Comparison of deep mutational scanning phenotypes to changes in clade growth" in the paper could precise the fact that only Omicron lineages were kept :)
